# Generated by Django 5.1.4 on 2024-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailEML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_eml", models.TextField()),
                ("email_message_id", models.CharField(max_length=995)),
                ("email_from", models.CharField(max_length=320)),
                (
                    "mailbot_recieve_date",
                    models.DateTimeField(verbose_name="mailbot_recieve_date"),
                ),
                (
                    "mailbot_update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="mailbot_update_date"
                    ),
                ),
            ],
        ),
    ]
